name: CrateSystem
description: CrateSystem Plugin adds crate to your server.
version: 1.0.2
api: [3.0.0-ALPHA11, 3.0.0-ALPHA12]
main: CrateSystem\Main
author: CLADevs Team
depend: [FormAPI] # By jojoe77777